# Generated by Django 2.1.1 on 2018-09-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniurl',
            name='shortcode',
            field=models.CharField(default='defaultshortcode', max_length=20),
            preserve_default=False,
        ),
    ]
